update_time = []

[agent]
active = true
file = '../agents/libcpu_check.so'
name = 'cpu'
started_at = '''Sat Aug 29 19:51:07 2026
'''
type = 'type1'

[[crit_value]]
name = 'cpu_usage'
value = '>50.000000'