update_time = []

[agent]
active = true
file = '../agents/libcpu_check.so'
name = 'cpu'
started_at = '''Sat Aug 22 13:43:39 2026
'''
type = 'type_cpu'

[[crit_values]]
name = ''
value = '=0.000000'

[[crit_values]]
name = 'cpu_usage'
value = '>90.000000'

[[crit_values]]
name = 'mem'
value = '=80.000000'