update_time = []

[agent]
active = true
file = '../agents/libswap_check.so'
name = 'swap1'
started_at = '''Sat Aug 29 19:50:02 2026
'''
type = 'swap_type'

[[crit_value]]
name = 'example_value'
value = '=0.000000'